export const BASE_API = "http://127.0.0.1:8000"
export const API_LOGIN = `${BASE_API}/api/auth/login`
export const API_LIST_USER = `${BASE_API}/api/auth/list`
export const API_REGISTER = `${BASE_API}/api/auth/register`
export const API_LOGOUT = `${BASE_API}/api/auth/logout`
export const API_MOVIES_STORE = `${BASE_API}/api/movies/store`
export const API_MOVIES = `${BASE_API}/api/movies`
export const API_LIST_ADVERTISEMENT =`${BASE_API}/api/advertise`
export const API_ADVERTISEMENT_STORE=`${BASE_API}/api/advertise/store`