export const HOME = '/'
export const USER ='/user'
export const MOVIE ='/movie'
export const MOVIE_MODIFY ='/movie_modify'
export const LOGIN='/login'
export const ADVERTISEMENT ='/advertisement'
export const ADVERTISEMENT_MODIFY ='/advertisement_modify'
